### ISSUE TITLE
consume not passing errors

### ISSUE THREAD

**Issue by mpj** [caolan/highland#136]
Given the code below, I except the console.error to output. Instead, the error is thrown (see error below)
```javascript
var _ = require('highland');

var brokenThroughStream = _().consume(function(err, x, push, next) {
  push(new Error('I BROKE'), null)
})

var a = _();

var b = a.through(brokenThroughStream)

b
  .errors(function(err){
    console.error('I will never output :(')
  })
  .resume()

a.write("something")
```

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: I BROKE
    at /Users/mpj/code/request-through/error-handling-through.js:4:8
    at Stream.s._send (/Users/mpj/code/request-through/node_modules/highland/lib/index.js:1021:9)
    at Stream.write (/Users/mpj/code/request-through/node_modules/highland/lib/index.js:1094:18)
    at /Users/mpj/code/request-through/node_modules/highland/lib/index.js:790:23
    at Stream.s._send (/Users/mpj/code/request-through/node_modules/highland/lib/index.js:1021:9)
    at Stream.write (/Users/mpj/code/request-through/node_modules/highland/lib/index.js:1094:18)
    at Stream._send (/Users/mpj/code/request-through/node_modules/highland/lib/index.js:571:19)
    at Stream.write (/Users/mpj/code/request-through/node_modules/highland/lib/index.js:1094:18)
    at Object.<anonymous> (/Users/mpj/code/request-through/error-handling-through.js:17:3)
    at Module._compile (module.js:456:26)
```

**Comment by vqvu** [comment]
I've been thinking about this because of the PR that @svozza recently submitted.

Isn't the problem here that "`through` doesn't propagate errors like Highland streams" and not "`pipe` doesn't propagate errors like Highland streams"? So then isn't the solution to reimplement `through` so that it works (even if we have to stop implementing it with `pipe`.

It seems to me that `pipe` is imitating node stream pipes, which normally throws if there are no handlers registered. `through` is the highland version of that, which will propagate errors. We shouldn't break one to fix the other.

Isn't it weird behavior to have some node writable streams throw and some don't (highland streams) when passed to `pipe`?

**Comment by vqvu** [comment]
I think not changing `pipe` also has the added advantage of not breaking back compat (if we consider `through` throwing a bug), so we don't need to wait until 3.0.

**Comment by LewisJEllis** [comment]
+1; one sticking point was the inconsistency between hl#pipe and node#pipe, and this change would unify that behavior /and/ solve the original problem with through.
