### ISSUE TITLE
.through() should throw explanatory error if not passed a stream

### ISSUE THREAD

**Issue by mpj** [caolan/highland#268]

**Comment by vqvu** [comment]
How would you detect a stream? We want to support anything that looks like a through stream.

We could check for the appropriate methods, but that's no guarantee of anything. Not to mention these kinds of checks aren't really in the spirit of duck typing.

**Comment by mpj** [comment]
Eh, I think this issue is now misnamed, I just quickly created it as a note to myself to submit a PR for a check because I initially thought it was easier than it is.

I'll explain the reason behind the issue instead and you can determine if it's valid or not.

The reason I submitted the issue was that I had been writing an inspector stream that looked something like this (Inspired by https://github.com/caolan/highland/issues/148#issuecomment-64073231)
```javascript
var _ = require('highland')

var inspector = _.curry(function inspector(name, stream) {
    return stream.map(function (val) {
        console.log("Inspector with name", name, "saw", val)
        return val;
    });
})

_([1, 2, 3, 4]).through(inspector('Smith')).toArray(_.log);
```

The problem was that I had forgotten to call the function:
```javascript
_([1, 2, 3, 4]).through(inspector).toArray(_.log);
```

Which yields this error message:

```_([1, 2, 3, 4]).through(inspector).toArray(_.log);
                                   ^
TypeError: Object function () {
        return f.apply(this, args.concat(slice.call(arguments)));
    } has no method 'toArray'
    at Object.<anonymous> (/Users/mpj/code/alladin/hum.js:10:36)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3
```
Which I thought could be a bit more helpful. 

Same error would occur if I called it without the first arg:
```javascript
_([1, 2, 3, 4]).through(inspector).toArray(_.log);
```

**Comment by vqvu** [comment]
I see the problem. It's technically possible to check that the function passed to `through` returns a highland stream by using `_.isStream`.

However, I can see a valid use case for using `through` to implement a custom transform to that wouldn't return a highland stream.

For example, `through` could be used with the top-level version of one of the terminal transforms (like `_.apply`). Or it could be implementing a converter like `toPromise`. The docs don't specifically say the function must return a highland stream, and I think the `toPromise` (and similar) use cases are useful enough that we wouldn't want to enforce that condition.
