### ISSUE TITLE
how to destroy a stream cleanly

### ISSUE THREAD

**Issue by benjaminhon** [caolan/highland#489]
Hi All, here is my issue
`
// many clients will connect and pipe their data into mainStream
net.createServer (socket) ->
    clientStream = h(socket)
    clientStream.fork().pipe mainStream
`

However, my question is what happens the the socket closes, does highland destroys clientStream and unpipes it from mainStream?

When i disconnect and connect the client 11 times i get this warning:
`
(node) warning: possible EventEmitter memory leak detected. 11 drain listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Stream.addListener (events.js:239:17)
    at pipeStream (/Users/benjaminhon/Developer/IndoorLocalization/server/localization-server/node_modules/highland/lib/index.js:501:10)
    at Stream.pipe (/Users/benjaminhon/Developer/IndoorLocalization/server/localization-server/node_modules/highland/lib/index.js:1008:12)
`

it seems some event listeners are not removed? do i need to do this manually and unripe manually?

Thx

**Comment by vqvu** [comment]
Highland should destroy `clientStream` when the socket ends and remove its `drain` listener. I had no problems connecting and disconnecting to the server more than 11 times without seeing this message. I simply started and stopped `telnet` 12 times.

Are you sure there aren't 12 *concurrent* clients connected to the server when this message appears?

The other possibility is that the socket closed without the stream noticing. This used to happen if the underlying Readable emits `close` without emitting `end`, and was very recently fixed in #479. I'm not sure if sockets can behave this way, but can you test against the latest `master` to see if you still have this problem? I haven't gotten around to releasing the fix to NPM yet.

**Comment by benjaminhon** [comment]
Hi victor, 

yep, its only 1 client. Yea there is no way that i can ensure that END happens before CLOSE, as the device might crash or terminated without closing the socket properly. I've noticed that sometimes CLOSE happens and END does not happen.

**Comment by vqvu** [comment]
You should be able to do `socket.on('close', () => clientStream.destroy())`.

**Comment by benjaminhon** [comment]
Hmm it seems the problem seems to be the piping function not disassociating itself properly when the socket ENDS or CLOSES

when socket ENDS of CLOSES, it seems all the forks terminates well and i don't get any leaks
```
deviceStream = h(socket)
deviceStream.fork().each (x) -> console.log x
```

however, if i consume it with pipe, then it seems when socket closes, the pipe is not disassociated correctly. I've confirmed that i received the END event though. So perhaps its another problem?
```
deviceStream = h(socket)
deviceStream.fork().pipe nodeStream
```

**Comment by benjaminhon** [comment]
Sorry, a correction, 
```
socket.on('close', () => clientStream.destroy())
```
does indeed remove the 'drain' listener from. I had a look at the source code for the pipeStream function
```
dest.on('drain', onConsumerDrain);

src._destructors.push(function () {
    dest.removeListener('drain', onConsumerDrain);
});
```

so i guess that when the socket CLOSES, its destructor is not called, thus needed us to manually call destroy() the stream

**Comment by vqvu** [comment]
> doesn't seem that the unpipe() function from node streams is exposed in the highland api?

Highland streams aren't Node streams. `pipe` is provided for interop with node streams, but we don't support `unpipe`.

> Mainly that the source highland stream is not destroying itself when the socket closes (even when both END and CLOSE events are present).

If this happens, then it is a bug. I can't reproduce though. Can you give me a test case?

**Comment by benjaminhon** [comment]
On the client do the following many times, after 11 times there will be a warning for 'drain' listener leaks
```
nc 192.168.123.123 9900
CTRL+C
nc 192.168.123.123 9900
CTRL+C
nc 192.168.123.123 9900
CTRL+C
nc 192.168.123.123 9900
CTRL+C
...
```

Here is the Server Code, manually calling deviceStream.destroy(), fixes it
```
  net.createServer (socket) ->
    console.error "#{socket.remoteAddress}:#{socket.remotePort} connected"

    # combine stream
    clientStream = h(socket)
    clientStream.pipe(mainStream, end: false)

    # disconnected
    socket.on 'close', ->
      console.error "#{socket.remoteAddress}:#{socket.remotePort} disconnected"
      # destroy stream, MUST CALL THIS
      deviceStream.destroy()

  # listen
  .listen env.tcpPort, ->
    console.error "tcp server listening on port #{env.tcpPort}"

**Comment by vqvu** [comment]
I couldn't reproduce when setting `mainStream` to `process.stdout` (even when setting `mainStream.setMaxListeners(1)`). I also couldn't do it with a `new stream.Writable({highWaterMark: 1})`.

However, I do see the behavior when I send something with `nc`. After sending something from 11 clients, the one immediately after the 11th client causes the error to appear. I could interleave those 11 clients with ones that don't send anything, and they don't end up counting against the 11 clients.

I think your problem is that `mainStream` is either slow or paused. A Highland stream will not do the cleanup until after it has emitted all of its data. If `mainStream` is exerting backpressure because it is slow at consuming data, then `clientStream` will pause until `mainStream` is ready for more. This means that `clientStream` may still be in the process of piping to `mainStream` even though the client has already disconnected. Hence why it looks like a memory leak.

Calling `destroy` forcibly destroys the `clientStream`, which is why it seems to fix things in this case. The problem is that if you `destroy` while there is data still buffered in the `socket`, you will lose the buffered data.

**Comment by benjaminhon** [comment]
Hmm yea my mainStream is always processing data, it is never consumed as i need to continually process data with it.

**Comment by vqvu** [comment]
That makes sense. Can you verify that it's not exerting backpressure on the `clientStreams`? If new clients stop connecting, does the `mainStream` eventually drain its sources and result in the handlers removed?

Without having a concrete implementation for `mainStream`, I can't tell whether or not this is a bug in Highland or just the `mainStream` being a bit slow at processing data.

**Comment by benjaminhon** [comment]
Hmm, so far the data seems to be processed in time. However, i use batchWithTimeOrCount. Here is whats done to the mainstream.

```
mainJSONStream = mainStream
  .split()
  .map(parseJSON)
  .reject (x) -> x is null

infoStream = mainJSONStream.fork()
  .filter (x) -> x.info?
  .each ({info: {node, major, minor, nodeBatt}}) ->
   ...[some processing]...

dataStream = mainJSONStream.fork()
  .filter (x) -> x.data?
  .map ({data}) -> data
  .batchWithTimeOrCount 1000, Infinity
  .through movingWindow(4)
  .map (arr) ->
  .each (raw) ->
    ...[some processing]...
```

**Comment by vqvu** [comment]
Hmm...nothing jumps out at me. `batchWithTimeOrCount` doesn't exert backpressure by itself. I don't know how `movingWindow` is implemented, but I can't imagine a reasonable implementation affecting anything.

I assume `mainStream` is defined like this?
```javascript
var mainStream = h();
```

I tried something like this and couldn't provoke the error.

```javascript
var mainJSONStream = mainStream.split()
    .map(JSON.parse)
    .reject(x => x == null);

var infoStream = mainJSONStream.fork()
    .filter(x => x.info)
    .each(y => _.log('Y: ' + JSON.stringify(y)));

var dataStream = mainJSONStream.fork()
    .filter(x => x.data)
    .map(x => x.data)
    .batchWithTimeOrCount(5000, Infinity)
    .each(x => _.log('X: ' + JSON.stringify(x)));
```

If you haven't done so already, can you bind a `removeListener` handler on `mainStream` to see if the listeners are actually being removed?

```javascript
mainStream.on('removeListener', event => {
    if (event === 'drain') {
        console.log('drain listener removed');
    }
});
```

Then remove the call to `destroy` and try to force the memory leak message to appear again. Once it does, stop connecting with clients and see if the drain listeners are all removed after a while.

Also, [you are using v2.7.3+ right](https://github.com/caolan/highland/blob/master/CHANGELOG.md#273)?

**Comment by benjaminhon** [comment]
Hmm nope i am using v2.7.1

```
var mainStream = h();
```

**Comment by vqvu** [comment]
2.7.3 fixes a `drain` listener memory leak, so upgrading may fix the problem for you.
